#!/usr/bin/python3
import os
import py_compile
py_file = os.environ.get('PYFILE')

if py_file:
    # Set the destination filename with the trailing 'c'
    c_file = py_file + "c"
    print("Compiling {} ...".format(py_file))
    py_compile.compile(py_file, cfile=c_file)
